### ISSUE TITLE
Not working on Android 4.4.2

### ISSUE THREAD

**Issue by DCareClues** [caffeinalab/ti.goosh#12]
[DEBUG] :  D/ti.goosh.TiGooshModule: No notification in Intent
[ERROR] :  GooglePlayServicesUtil: The Google Play services resources were not found. Check your project configuration to ensure that the resources are included.
[WARN] :   GooglePlayServicesUtil: Google Play services out of date.  Requires 8487000 but found 7895032
[WARN] :   W/System.err: java.lang.NoClassDefFoundError: com.google.android.gms.R$string
[WARN] :   W/System.err: 	at com.google.android.gms.common.internal.zzg.zzc(Unknown Source)
[WARN] :   W/System.err: 	at com.google.android.gms.common.GooglePlayServicesUtil.zza(Unknown Source)
[WARN] :   W/System.err: 	at com.google.android.gms.common.GooglePlayServicesUtil.getErrorDialog(Unknown Source)
[WARN] :   W/System.err: 	at com.google.android.gms.common.GooglePlayServicesUtil.getErrorDialog(Unknown Source)
[WARN] :   W/System.err: 	at com.google.android.gms.common.GoogleApiAvailability.getErrorDialog(Unknown Source)
[WARN] :   W/System.err: 	at ti.goosh.TiGooshModule.checkPlayServices(TiGooshModule.java:89)
[WARN] :   W/System.err: 	at ti.goosh.TiGooshModule.registerForPushNotifications(TiGooshModule.java:114)
[WARN] :   W/System.err: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.nativeRunModule(Native Method)
[WARN] :   W/System.err: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.doRunModule(V8Runtime.java:177)
[WARN] :   W/System.err: 	at org.appcelerator.kroll.KrollRuntime.handleMessage(KrollRuntime.java:319)
[WARN] :   W/System.err: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.handleMessage(V8Runtime.java:203)

**Comment by kopiro** [comment]
Make sure that you have inserted in your tiapp.xml, in the node **android> manifest > application**, the GPS ver:

```xml<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
```

**Comment by jmosqueda1987** [comment]
Hi, I have the same problem, but dont work, this is my code in tiapp.xml

<pre>

<android xmlns:android="http://schemas.android.com/apk/res/android">
    	<manifest android:versionCode="1000" android:versionName="1.0.0" package="com.imp.dev" xmlns:android="http://schemas.android.com/apk/res/android">
    		<application android:theme="@style/Theme.AppCompat.Light.NoActionBar">
    		 	<meta-data
    android:name="com.google.android.gms.version"
    android:value="@integer/google_play_services_version" />
    		 </application>
    	</manifest>
    </android>

</pre> 
Can you helpme?

**Comment by progress44** [comment]
@jmosqueda1987 Can you paste the error log?

**Comment by jmosqueda1987** [comment]
Sure! 

This is my error

Error: The meta-data tag in your app's AndroidManifest.xml does not have the right value.  Expected 7571000 but found 8487000.  You must have the following declaration within the <application> element:     <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />


Thanks!

**Comment by kopiro** [comment]
Are you using other Android modules?

**Comment by jmosqueda1987** [comment]
Thanks for fast response!

Exactly, currently use also Ti.map


Regards

**Comment by kopiro** [comment]
Fast answer: https://github.com/caffeinalab/ti.goosh/tree/master/gps-jars
Chek why: https://github.com/caffeinalab/ti.goosh/issues/15

**Comment by jmosqueda1987** [comment]
Hi, 


Already copy the file google-play-services-gcm-map.jar to the ti.map and ti.goosh but get this error

[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/ads/identifier/AdvertisingIdClient;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/ads/identifier/AdvertisingIdClient$Info;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/AccountPicker;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/ConnectionResult;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/ErrorDialogFragment;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/GoogleApiAvailability;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/GooglePlayServicesNotAvailableException;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/GooglePlayServicesRepairableException;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/GooglePlayServicesUtil;

Thanks

**Comment by jmosqueda1987** [comment]
I delete all files en ti.map and get this error


[ERROR] :  Failed to run dexer:
[ERROR] :  
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/AccountPicker;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/ConnectionResult;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/ErrorDialogFragment;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/GoogleApiAvailability;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/GooglePlayServicesNotAvailableException;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/GooglePlayServicesRepairableException;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/GooglePlayServicesUtil;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/GooglePlayServicesUtil$zza;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/Scopes;
[ERROR] :  
[ERROR] :  UNEXPECTED TOP-LEVEL EXCEPTION:
[ERROR] :  java.lang.RuntimeException: Translation has been interrupted
[ERROR] :  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:608)
[ERROR] :  	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
[ERROR] :  	at com.android.dx.command.dexer.Main.run(Main.java:277)
[ERROR] :  	at com.android.dx.command.dexer.Main.main(Main.java:245)
[ERROR] :  	at com.android.dx.command.Main.main(Main.java:106)
[ERROR] :  Caused by: java.lang.InterruptedException: Too many errors
[ERROR] :  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:600)
[ERROR] :  	... 4 more


Please help me

Thanks

**Comment by progress44** [comment]
@jmosqueda1987 are you using any other module that makes use of google play services?

**Comment by jmosqueda1987** [comment]
I Think That only ti.map , recently i delete tuve jar in ti.map/lib and ti.goosh/lib and it's Work but I don't know if this is bad , what do you think ???  

Regards  
Thanks  

--  
kenhack@outlook.com  

El día 2 de septiembre de 2016 a las 2:10:44 p.m., Ani Sinanaj (notifications@github.com(mailto:notifications@github.com)) escrito:

**Comment by progress44** [comment]
@jmosqueda1987  I don't recall seeing tuve.jar in ti.map. You should be alright without it
