### ISSUE TITLE
Android google-play-services-gcm+maps.jar problem  

### ISSUE THREAD

**Issue by kassemitani** [caffeinalab/ti.goosh#81]
I have a problem with **google-play-services-gcm+maps.jar** on Android
`Rejecting re-init on previously-failed class java.lang.Class<ti.map.TiUIMapView>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/maps/GoogleMap$OnCameraMoveStartedListener;`

The Android app crashes on NoClassDefFoundError for OnCameraMoveStartedListener as i am using 
Ti.Map version: 3.4.0
Titanium SDK:  <sdk-version>6.1.2.GA</sdk-version>

Kindly generate a new jar file with  OnCameraMoveStartedListener class for  **google-play-services-gcm+maps.jar**

**Comment by progress44** [comment]
The module was using an old version of Google Play Services. Try the new release version 3.0.0 as it should fix this issue

**Comment by kassemitani** [comment]
@progress44 Thank you its now working fine with the version3.0.0 and the new .aar android library instead of the jar library 👍
